version: '3.4'

services:
  web:
    image: portfolio_tracker_demo
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./envs/deploy.env