version: '3.4'

services:

  web:
    image: gfudulov/portfolio_tracker
    build: .
    command: gunicorn --config ./envs/gunicorn_config.py stock_portfolio_tracker.wsgi:application
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - ./envs/deploy.env
    volumes:
      - /portfolio_tracker/static:/app/static

  nginx:
    image: nginx:1.14.2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /portfolio_tracker/static:/app/static
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    links:
      - web

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email fudulov.georgi@gmail.com --agree-tos --no-eff-email -d portfolio-tracker.com
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt