# Generated by Django 4.2.5 on 2023-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker_stocks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='average_purchase_price',
            field=models.PositiveIntegerField(default=110),
            preserve_default=False,
        ),
    ]
