# Generated by Django 4.2.5 on 2023-09-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker_stocks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
