# Generated by Django 4.2.5 on 2023-09-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker_stocks', '0003_profile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='realised_pnl',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity_sold', models.FloatField(default=0)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_tracker_stocks.profile')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_tracker_stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity_bought', models.FloatField(default=0)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_tracker_stocks.profile')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_tracker_stocks.stock')),
            ],
        ),
    ]
