# Generated by Django 4.2.5 on 2023-09-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker_stocks', '0005_alter_buy_quantity_bought_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='buy',
            name='quantity_bought',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='realised_pnl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='average_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
