# Generated by Django 4.2.5 on 2023-09-12 07:51

from django.db import migrations
import stock_portfolio_tracker.stock_tracker_users.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', stock_portfolio_tracker.stock_tracker_users.models.UserManager()),
            ],
        ),
    ]
