# Generated by Django 4.2.5 on 2023-10-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'User with this email address already exists.'}, max_length=254, unique=True),
        ),
    ]
